package UW::Model::WindyDB;
use lib '/opt/oracle/product/11.2.0/dbhome_1/perl/lib/site_perl/5.10.0/i686-linux-thread-multi/';
use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'UW::Schema',
    
    connect_info => {
        dsn => 'dbi:Oracle:oraUW',
        user => 'UW',
        password => 'windy123',
	{oracharset => 'AL32UTF8'}
    }
);

=head1 NAME

UW::Model::WindyDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<UW>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<UW::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.38

=head1 AUTHOR

xyf

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
